-- Add Profile Fields to tbl_users
ALTER TABLE tbl_users
ADD COLUMN profile_picture VARCHAR(255) DEFAULT NULL,
ADD COLUMN phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN city VARCHAR(100) DEFAULT NULL,
ADD COLUMN state VARCHAR(100) DEFAULT NULL,
ADD COLUMN zip VARCHAR(20) DEFAULT NULL,
ADD COLUMN country VARCHAR(100) DEFAULT NULL;
